name: Yangi imkoniyat taklifi
about: Yulemdo uchun yangi g‘oya yoki imkoniyat taklif qiling
title: "[FEATURE] "
labels: enhancement
assignees: ''

body:
  - type: textarea
    id: problem
    attributes:
      label: Qaysi muammoni hal qiladi?
      description: Bu imkoniyat kimga va qanday foyda beradi?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Taklif qilinayotgan yechim
      description: G‘oyangizni iloji boricha aniq tasvirlang.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Muqobil variantlar
      description: Qanday boshqa yechimlarni ko‘rib chiqdingiz?

  - type: textarea
    id: additional
    attributes:
      label: Qo‘shimcha ma’lumot
      description: Misollar, dizaynlar yoki havolalarni qo‘shing.
